In [27]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from datetime import timedelta

In [2]:
def GetSentiment(df=None, column=None, prefix=''):
    from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
    #from nltk.sentiment.vader import SentimentIntensityAnalyzer
    sia = SentimentIntensityAnalyzer()
    Sent = df[[column]].copy()
    Sent[prefix+'compound'] = Sent[column].apply(lambda x: sia.polarity_scores(x)['compound'])
    Sent[prefix+'neutral'] = Sent[column].apply(lambda x: sia.polarity_scores(x)['neu'])
    Sent[prefix+'positive'] = Sent[column].apply(lambda x: sia.polarity_scores(x)['pos'])
    Sent[prefix+'negative'] = Sent[column].apply(lambda x: sia.polarity_scores(x)['neg'])
    return Sent.iloc[:,1:]

In [3]:
def GetSubjectivity(df=None, column=None, prefix=''):
    from textblob import TextBlob
    Sub = df[[column]].copy()
    Sub[prefix+'subjectivity'] = Sub[column].apply(lambda x: TextBlob(x).sentiment.subjectivity )
    return Sub.iloc[:,1:]

In [6]:
import os
os.getcwd()

'/Users/cysung/GA/projects/project_capstone/part_02'

In [7]:
#def GetStats(csvfile=None):
df = pd.read_csv('2_42-grams_review.csv')

In [10]:
df.shape

(80, 3)

In [12]:
df

          date  star                                               text
0   2017-07-17   5.0  We are sad to hear of 42 grams closing. We had...
1   2017-05-16   5.0  A gold standard in fine dining.  Jake and Alex...
2   2017-04-25   5.0  Wow... this is an experience.    Probably top ...
3   2017-03-17   5.0  What an excellent dining experience! One of th...
4   2017-03-09   5.0  Of all the fine dining experiences I have had ...
5   2017-01-05   5.0  Overall , amazing. Food worth all the praise p...
6   2016-12-03   5.0  Fantastic. Extremely personable between the ch...
7   2016-11-22   5.0  Absurd.  You will not forget eating here.  One...
8   2016-11-12   5.0  42 grams provides a unique dining experience t...
9   2016-11-11   4.0  went there last year for our anniversary last....
10  2016-11-10   3.0  Service was great, and the stories/description...
11  2016-11-09   5.0  14 April 2016 - We were very fortunate to get ...
12  2016-11-06   5.0  Celebrating our 6th anniversary with my hero's...
13  2016-11-06   1.0  I can't believe this place has 2 stars. Alexia...
14  2016-11-05   5.0  42 grams is crazy good! They deserve their two...
15  2016-11-03   1.0  we booked months in advance, of course they im...
16  2016-10-08   5.0  ***The very personal and intimate 42 grams is ...
17  2016-09-13   5.0  Wow. I made a reservation 3 months in advance ...
18  2016-09-05   5.0  A unique experience no doubt. Pretend you are ...
19  2016-08-11   5.0  This is a review tailored towards those among ...
20  2016-07-22   5.0  Loved Alexa and Jake. The setup is very comfor...
21  2016-06-30   5.0  Outstanding!  My friend and I have been trying...
22  2016-05-31   5.0  Amazing experience done by 2 very kind, friend...
23  2016-05-30   5.0  This was the best meal have had in Chicago in ...
24  2016-05-20   5.0  Been here before they got 2 Michelin stars.  B...
25  2016-04-26   3.0  Dined here on our recent trip to Chicago last ...
26  2016-03-21   5.0  when you think about the top 5 memorable meals...
27  2016-02-07   5.0  I would highly recommend eating at 42 grams; i...
28  2016-01-02   5.0  This review is LONG overdue. In short, the bes...
29  2015-12-15   4.0  There is a lot of good going on at 42 grams, a...
..         ...   ...                                                ...
50  2014-12-19   5.0  Let me start by saying that while we have been...
51  2014-12-18   5.0  Wow. Just wow. Get there before you can't. Onl...
52  2014-12-09   5.0  It took me a while to write this review (I vis...
53  2014-11-21   1.0  I decided this was where I wanted to celebrate...
54  2014-11-11   5.0  My husband and I came here last weekend for ou...
55  2014-10-20   1.0  This is the kind of correspondence you should ...
56  2014-09-20   5.0  This had to have been the best meal of the yea...
57  2014-09-15   5.0  One of the best meals I've ever had in Chicago...
58  2014-08-26   5.0  This is definitely a special occasion place.  ...
59  2014-08-11   5.0  Had the pleasure of being in 42 Grams first se...
60  2014-08-09   5.0  I really enjoyed dining at the counter. I sugg...
61  2014-07-27   5.0  An intimate and adventurous experience.  All f...
62  2014-07-20   5.0  Amazing experience last night at the communal ...
63  2014-06-30   5.0  I had the best single dish I've ever had at th...
64  2014-05-29   3.0  The food was excellent but a bit pricey.   My ...
65  2014-05-19   4.0  For my first ticketed 10+ course restaurant I ...
66  2014-05-17   3.0  I think this place has a lot of potential, but...
67  2014-05-04   5.0  What a wonderful experience! Intimate, delicio...
68  2014-04-19   3.0  Nice. Recommended - but no tap water please! S...
69  2014-03-29   5.0  Amazing food, owners are amazing, this is my n...
70  2014-03-29   5.0  I had a pleasure of being introduced to Jake's...
71  2014-03-16   5.0  A simply amazing experience. Chef  Jake and hi...
72  2014-03-02   5.0  Enjoyed my time at the Chef's Counter on Frida...
73  2014-02-15   5.0  Simply a fantastic dining experience. Alexa an...
74  2014-02-09   5.0  The place is a welcome addition to the Uptown ...
75  2014-01-29   5.0  This was literally one of the best meals of my...
76  2014-01-22   5.0  My husband surprised me with dinner here to ce...
77  2014-01-16   5.0  just had a fabulous dinner. intimate setting a...
78  2014-01-13   5.0  Absolutely fantastic! We went with a group of ...
79  2014-01-11   5.0  I've heard great things about sous rising and ...

[80 rows x 3 columns]

In [13]:
df.shape[0]

80

In [18]:
last = df['date'][0]

In [19]:
type(last)

str

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 3 columns):
date    80 non-null object
star    80 non-null float64
text    80 non-null object
dtypes: float64(1), object(2)
memory usage: 2.0+ KB

In [22]:
df['date'] =  pd.to_datetime(df['date'])

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 3 columns):
date    80 non-null datetime64[ns]
star    80 non-null float64
text    80 non-null object
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 2.0+ KB

In [25]:
df['date'][0]

Timestamp('2017-07-17 00:00:00')

In [44]:
daysago = 365
#td = timedelta(days=daysago)

In [45]:
timepoint = df['date'][0] - timedelta(days=daysago)

In [34]:
oneyago = df['date'][0] - td

In [33]:
df['date'][0] > ago

True

In [35]:
twoyago = df['date'][0] - timedelta(days=720)

In [37]:
oneyago

Timestamp('2016-07-17 00:00:00')

In [36]:
twoyago

Timestamp('2015-07-28 00:00:00')

In [38]:
twoyago > oneyago

False

In [41]:
recent = df[df['date'] > oneyago]

In [42]:
recent

         date  star                                               text
0  2017-07-17   5.0  We are sad to hear of 42 grams closing. We had...
1  2017-05-16   5.0  A gold standard in fine dining.  Jake and Alex...
2  2017-04-25   5.0  Wow... this is an experience.    Probably top ...
3  2017-03-17   5.0  What an excellent dining experience! One of th...
4  2017-03-09   5.0  Of all the fine dining experiences I have had ...
5  2017-01-05   5.0  Overall , amazing. Food worth all the praise p...
6  2016-12-03   5.0  Fantastic. Extremely personable between the ch...
7  2016-11-22   5.0  Absurd.  You will not forget eating here.  One...
8  2016-11-12   5.0  42 grams provides a unique dining experience t...
9  2016-11-11   4.0  went there last year for our anniversary last....
10 2016-11-10   3.0  Service was great, and the stories/description...
11 2016-11-09   5.0  14 April 2016 - We were very fortunate to get ...
12 2016-11-06   5.0  Celebrating our 6th anniversary with my hero's...
13 2016-11-06   1.0  I can't believe this place has 2 stars. Alexia...
14 2016-11-05   5.0  42 grams is crazy good! They deserve their two...
15 2016-11-03   1.0  we booked months in advance, of course they im...
16 2016-10-08   5.0  ***The very personal and intimate 42 grams is ...
17 2016-09-13   5.0  Wow. I made a reservation 3 months in advance ...
18 2016-09-05   5.0  A unique experience no doubt. Pretend you are ...
19 2016-08-11   5.0  This is a review tailored towards those among ...
20 2016-07-22   5.0  Loved Alexa and Jake. The setup is very comfor...

In [47]:
df.shape[0]

80

In [53]:
oneyear = 365
twoyear = 730

In [54]:
timepoint1 = df['date'][0] - timedelta(days=oneyear)
timepoint2 = df['date'][0] - timedelta(days=twoyear)
recent = df[df['date'] > timepoint1]
if recent.shape[0] >= 50:
    df = recent.copy()
else:
    df = df[df['date'] > timepoint2]

In [55]:
df

         date  star                                               text
0  2017-07-17   5.0  We are sad to hear of 42 grams closing. We had...
1  2017-05-16   5.0  A gold standard in fine dining.  Jake and Alex...
2  2017-04-25   5.0  Wow... this is an experience.    Probably top ...
3  2017-03-17   5.0  What an excellent dining experience! One of th...
4  2017-03-09   5.0  Of all the fine dining experiences I have had ...
5  2017-01-05   5.0  Overall , amazing. Food worth all the praise p...
6  2016-12-03   5.0  Fantastic. Extremely personable between the ch...
7  2016-11-22   5.0  Absurd.  You will not forget eating here.  One...
8  2016-11-12   5.0  42 grams provides a unique dining experience t...
9  2016-11-11   4.0  went there last year for our anniversary last....
10 2016-11-10   3.0  Service was great, and the stories/description...
11 2016-11-09   5.0  14 April 2016 - We were very fortunate to get ...
12 2016-11-06   5.0  Celebrating our 6th anniversary with my hero's...
13 2016-11-06   1.0  I can't believe this place has 2 stars. Alexia...
14 2016-11-05   5.0  42 grams is crazy good! They deserve their two...
15 2016-11-03   1.0  we booked months in advance, of course they im...
16 2016-10-08   5.0  ***The very personal and intimate 42 grams is ...
17 2016-09-13   5.0  Wow. I made a reservation 3 months in advance ...
18 2016-09-05   5.0  A unique experience no doubt. Pretend you are ...
19 2016-08-11   5.0  This is a review tailored towards those among ...
20 2016-07-22   5.0  Loved Alexa and Jake. The setup is very comfor...
21 2016-06-30   5.0  Outstanding!  My friend and I have been trying...
22 2016-05-31   5.0  Amazing experience done by 2 very kind, friend...
23 2016-05-30   5.0  This was the best meal have had in Chicago in ...
24 2016-05-20   5.0  Been here before they got 2 Michelin stars.  B...
25 2016-04-26   3.0  Dined here on our recent trip to Chicago last ...
26 2016-03-21   5.0  when you think about the top 5 memorable meals...
27 2016-02-07   5.0  I would highly recommend eating at 42 grams; i...
28 2016-01-02   5.0  This review is LONG overdue. In short, the bes...
29 2015-12-15   4.0  There is a lot of good going on at 42 grams, a...
30 2015-12-11   5.0  Great food. Exotic taste. It's BYOB because th...
31 2015-12-03   4.0  It was more of a 3.5 but whatevs. Easy online ...
32 2015-10-15   5.0  Absolutely delicious.....the best meal so far ...
33 2015-10-13   4.0  OMG.   Just not sure it deserves the 5 stars. ...
34 2015-10-02   2.0  Disappointing.  Very rushed, for one thing.  T...
35 2015-08-16   5.0  Overall, I felt that 42 grams served the best ...
36 2015-07-30   5.0  Doesn't get much better than this.  13 courses...

In [ ]:
if df.shape[0] > 50:
    timepoint = df['date'][0] - timedelta(days=daysago)
    recent = df[df['date'] > timepoint]
    if recent.shape[0] < 50